/**
 * @author Erik Desjardins
 * See LICENSE file in root directory for full license.
 */

'use strict';

var fs = require('fs');
var path = require('path');
var loaderUtils = require('loader-utils');

module.exports = function() {};

// https://github.com/webpack/webpack/blob/5abfeea64bcfe4f60f1c79eb1ba95686dc857faa/lib/NormalModuleFactory.js#L118
// for using `pitching-loader?query!` (no resource)

module.exports.pitch = function() {
	var callback = this.async();

	var options = Object.assign({ match: /\.js$/i }, loaderUtils.getOptions(this));
	var match = typeof options.match === 'string' ? new RegExp(options.match, 'i') : options.match;
	var context = path.join(this.context || this._module.issuer.context, options.path);

	// add context dependency so new files are picked up
	this.addContextDependency(context);

	fs.readdir(context, function(err, files) {
		if (err) return callback(err);

		var matchingFiles = files
			.filter(function(filename) {
				return match.test(filename);
			})
			.map(function(filename, i) {
				return {
					name: filename,
					id: '_' + i
				};
			});

		var header = '/* generated by contents-loader */';

		var importStatements = matchingFiles
			.map(function(info) {
				return 'import * as ' + info.id + ' from ' + JSON.stringify(path.join(context, info.name)) + ';';
			})
			.join('\n');

		var exportStatement = 'export default { ' + matchingFiles
			.map(function(info) {
				return JSON.stringify(info.name) + ": " + info.id;
			})
			.join(', ') + ' };';

		callback(null, [header, importStatements, exportStatement].join('\n'));
	});

	return '';
};
