/**
 * @author Erik Desjardins
 * See LICENSE file in root directory for full license.
 */

'use strict';

var fs = require('fs');
var path = require('path');
var loaderUtils = require('loader-utils');

module.exports = function() {};

module.exports.pitch = function(request) {
	if (!request.endsWith('/')) {
		throw new Error(
			'contents-loader: request "' + request + '" must have a trailing slash. ' +
			'Try "' + request + '/" instead.'
		);
	}

	var callback = this.async();

	var options = Object.assign({ match: /\.js$/i }, loaderUtils.getOptions(this));
	var match = typeof options.match === 'string' ? new RegExp(options.match, 'i') : options.match;

	// add context dependency so new files are picked up
	this.addContextDependency(request);

	fs.readdir(this.context, function(err, files) {
		if (err) return callback(err);

		var matchingFiles = files
			.filter(function(filename) {
				return match.test(filename);
			})
			.map(function(filename, i) {
				return {
					name: filename,
					id: '_' + i
				};
			});

		var header = '/* generated by contents-loader */';

		var importStatements = matchingFiles
			.map(function(info) {
				return 'import * as ' + info.id + ' from ' + JSON.stringify('.' + path.join('/', request, info.name)) + ';';
			})
			.join('\n');

		var exportStatement = 'export default { ' + matchingFiles
			.map(function(info) {
				return JSON.stringify(info.name) + ": " + info.id;
			})
			.join(', ') + ' };';

		callback(null, [header, importStatements, exportStatement].join('\n'));
	});

	return '';
};
